# Generated by Django 4.0.4 on 2022-05-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_alter_comments_author_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(blank=True, choices=[('back end', 'back end'), ('front end', 'front end'), ('iOS', 'iOS'), ('Android', 'Android')], default='back end', max_length=32),
        ),
    ]
